### ISSUE TITLE
Question: Using Local Packages with `debuerreotype-init`

### ISSUE THREAD

**Issue by andrespavez** [debuerreotype/debuerreotype#172]
Hello,
I am wondering if it is possible for `debuerreotype-init` to create the root filesystem from packages stored in a local directory. 
I need to run `debuerreotype-init` multiple times, and I've noticed that `snapshot.debian.org` can be slow or unresponsive at times.
 
For example, when installing packages, I use `apt-get` with the `--download-only` option to retrieve all the necessary packages based on the `epoch`, and then I install them directly from the local directory without having to download them again each time.

I would like to know if a similar approach is possible with `debuerreotype-init`.

Thanks.

**Comment by tianon** [comment]
Hmm, the way I personally handle this is by putting a local caching proxy in front of `snapshot.debian.org`, which is really reliable for me (every now and then I have to retry a build due to flakiness, but then it's much faster thanks to the local cache; see https://github.com/tianon/squignix if you're curious about the details of my cache configuration).

None of these scripts currently support a mode like what you've described (the closest in `debuerreotype-init` is the `--non-debian` flag which then takes a mirror, but immediately tries to download the `InRelease` file from it, which would fail for your local directory use case).
