### ISSUE TITLE
Remeove comments from /etc/apt/sources.list

### ISSUE THREAD

**Issue by cranebytes** [debuerreotype/debuerreotype#84]
If I update my rootfs with a new repository the previous mirror is still there but commented out.
This might be fine in most of the cases but when you start diffing your images for changes you get a false positve because of the timestamps.

Tianon helped me out with the tipp of removing it with a simple `sed -i -e '/^#/d'` (thanks for it! :)) but it is just lingering around something.

I don't see any reason to keep this information there. So my idea/wish would be to remove old stuff from the file to end up with a clean sources.list.
But if there is a reason to keep it (I would be interested if there is really one) then a commnd line option would be nice. Somethink like `--no-backup` or so.

**Comment by tianon** [comment]
> I don't see any reason to keep this information there.

The reason is mostly transparency -- letting users quickly and easily see exactly where the bits they're pulling originally came from.

Given the number of added lines for a new command-line flag compared to the very trivial `sed -i -e '/^#/d' /etc/apt/sources.list`, I'm afraid I'm just not convinced this is worth the maintenance burden; sorry!

(Users are also always free to not use `debuerrueotype-debian-sources-list` and just generate their own `sources.list`.)
