### ISSUE TITLE
docker images for raspbian linux/arm64, linux/arm/v6, linux/arm/v7?

### ISSUE THREAD

**Issue by rgl** [debuerreotype/debuerreotype#97]
@tianon, can you please start publishing raspbian linux/arm64, linux/arm/v6, linux/arm/v7 to https://hub.docker.com/r/tianon/raspbian? or even https://hub.docker.com/_/raspbian? :-)

Do you known why https://hub.docker.com/u/raspbian is not official?

I'm sorry if this is not the correct repo for this issue, but I didn't find a more suitable one.

Also, in order for the image to be more alike raspberry pi os I would like to customize it with the following:

```bash
echo 'deb http://archive.raspberrypi.org/debian/ buster main' >/etc/apt/sources.list.d/raspi.list && \
	gpg --keyserver keys.gnupg.net --recv-key 82B129927FA3303E && \
	gpg -a --export 82B129927FA3303E | apt-key add -
```

**NB** this is needed to be able to install the libraries that add support for accessing the rpi hardware (e.g. `/dev/vchiq` with the `libraspberrypi-dev/libraspberrypi0` library.

And maybe these apt.conf.d settings:

```plain
root@raspberrypi:~# cat /etc/apt/apt.conf.d/50raspi
# never use pdiffs. Current implementation is very slow on low-powered devices
Acquire::PDiffs "0";

# download up to 5 pdiffs:
#Acquire::PDiffs::FileLimit "5";

root@raspberrypi:~# cat /etc/apt/apt.conf.d/70debconf
// Pre-configure all packages with debconf before they are installed.
// If you don't like it, comment it out.
DPkg::Pre-Install-Pkgs {"/usr/sbin/dpkg-preconfigure --apt || true";};
root@raspberrypi:~# 
```

What do you think?

Should this be added to [raspbian.sh](raspbian.sh) or this should really be made in our Dockerfile?

**Comment by rgl** [comment]
I was able to use debian:buster-slim for what I wanted after all!

I did it at https://github.com/rgl/ustreamer/tree/rgl-docker-build-debian-buster-slim.

So maybe there is no need for a raspbian image? I'm not really sure if raspbian/debian have exactly the same lifecycle nor if the http://archive.raspberrypi.org/debian/ repository is supposed to work with both... right they work thou.

**Comment by tianon** [comment]
Raspbian upstream (as far as I understand) only supports arm32v6, by design.  This is because Debian already natively supports arm32v5, arm32v7, and arm64v8.  So for the two Raspberry Pi devices which are ARMv6 (RPi1 and RPi Zero), Raspbian exists to bridge the gap between v5 (which will always use emulated floating point instructions, and thus be much slower and less efficient on these devices) and v7 (which won't run on these two devices, but will on every newer device such as the RPi2, RPi3, RPi4, etc, assuming the kernel is appropriately compiled for their native architecture).

I'd love to make official Raspbian images under https://hub.docker.com/_/raspbian as part of the official images program properly, but I don't directly know any of the folks involved and I'm not sure where to contact them (so if someone else wants to chase that down and pitch the idea to them, I'm happy to be part of that conversation!).
